#!/bin/sh

ln -sf {{pkg.path}}/static/* {{pkg.svc_static_path}}
rm -rf "{{pkg.svc_static_path}}/config/secrets.yml" "{{pkg.svc_static_path}}/config/mongoid.yml"
ln -sf {{pkg.svc_config_path}}/secrets.yml {{pkg.svc_static_path}}/config/secrets.yml
ln -sf {{pkg.svc_config_path}}/mongoid.yml {{pkg.svc_static_path}}/config/mongoid.yml