production:
  clients:
    default:
      uri: {{cfg.mongodb_uri}}
      options:
        # The default timeout is 5, which is the time in seconds
        # for a connection to time out.
        # We recommend 15 because it allows for plenty of time
        # in most operating environments.
        connect_timeout: 15
        ssl: true